//Add non-agent stimuli picture filenames (240x360 px) and strings here
var stims = {
	stimDir: "",
	stimuli: [
		//"assistedsuicide.jpg",
		"filename1.jpg",
		"filename2.jpg",
		"filename3.jpg",
		"filename4.jpg",
		"filename5.jpg",
		"filename6.jpg",
		"filename7.jpg",
		"filename8.jpg",
		"filename9.jpg",
		"filename10.jpg",
		"filename11.jpg",
		"filename12.jpg",
		"filename13.jpg",
		"filename14.jpg",
		"filename15.jpg",
		"filename16.jpg",
		"filename17.jpg",
		"filename18.jpg",
		"filename19.jpg",
		"filename20.jpg",
		"filename21.jpg",
		"filename22.jpg",
		"filename23.jpg",
		"filename24.jpg",
		"filename25.jpg",
		"filename26.jpg",
		"filename27.jpg",
		"filename28.jpg",
		"filename29.jpg",
		"filename30.jpg",
		"filename31.jpg",
		"filename32.jpg"
	],
	prompts:[
		//"Should terminally ill patients be allowed to end their lives via assisted suicide?",
		"String 1 to go with filename1.jpg from above goes here.",
		"String 2 to go with filename2.jpg from above goes here.",
		"String 3 to go with filename3.jpg from above goes here.",
		"String 4 to go with filename4.jpg from above goes here.",
		"String 5 to go with filename5.jpg from above goes here.",
		"String 6 to go with filename6.jpg from above goes here.",
		"String 7 to go with filename7.jpg from above goes here.",
		"String 8 to go with filename8.jpg from above goes here.",
		"String 9 to go with filename9.jpg from above goes here.",
		"String 10 to go with filename10.jpg from above goes here.",
		"String 11 to go with filename11.jpg from above goes here.",
		"String 12 to go with filename12.jpg from above goes here.",
		"String 13 to go with filename13.jpg from above goes here.",
		"String 14 to go with filename14.jpg from above goes here.",
		"String 15 to go with filename15.jpg from above goes here.",
		"String 16 to go with filename16.jpg from above goes here.",
		"String 17 to go with filename17.jpg from above goes here.",
		"String 18 to go with filename18.jpg from above goes here.",
		"String 19 to go with filename19.jpg from above goes here.",
		"String 20 to go with filename20.jpg from above goes here.",
		"String 21 to go with filename21.jpg from above goes here.",
		"String 22 to go with filename22.jpg from above goes here.",
		"String 23 to go with filename23.jpg from above goes here.",
		"String 24 to go with filename24.jpg from above goes here.",
		"String 25 to go with filename25.jpg from above goes here.",
		"String 26 to go with filename26.jpg from above goes here.",
		"String 27 to go with filename27.jpg from above goes here.",
		"String 28 to go with filename28.jpg from above goes here.",
		"String 29 to go with filename29.jpg from above goes here.",
		"String 30 to go with filename30.jpg from above goes here.",
		"String 31 to go with filename31.jpg from above goes here.",
		"String 32 to go with filename32.jpg from above goes here."
	]
};
